name: Main

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: my-artifact.zip
          repository: danon/pack
          token: ${{ secrets.GITHUB_TOKEN }}
